apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: capitalist-lungfish-nodejs 
  janus-idp.io/tekton: capitalist-lungfish-nodejs
  backstage.io/kubernetes-id: capitalist-lungfish-nodejs
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: capitalist-lungfish-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  