apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: capitalist-lungfish-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: capitalist-lungfish-nodejs 
  name: capitalist-lungfish-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: capitalist-lungfish-nodejs 
